export const ActionsType = {
    DECREASE:'DECREASE',
    INCREASE:"INCREASE",
    REMOVE:"REMOVE",
    CLEAR_CART:"CLEAR_CART",
    GET_TOTAL_AND_AMOUNT:"GET_TOTAL_AND_AMOUNT",
    GET_ALL_PRODUCTS:"GET_ALL_PRODUCTS",
    TOGGLE_INCREASE_AND_DECREASE:"TOGGLE_INCREASE_AND_DECREASE"
}
